- name: Install nginx and start the service
  hosts: frontend
  tasks:
  become: true
    - name: Install nginx
      ansible.builtin.package:
        name: nginx
        state: present

    - name: start nginx
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes
